# Generated by Django 5.2.7 on 2025-10-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='delegation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
