# Generated by Django 5.2.7 on 2025-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_entreprise_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
