# Generated by Django 5.2.7 on 2025-10-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0003_entreprise_contact_alter_entreprise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contact'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('fonction', models.CharField(max_length=100, verbose_name="Fonction dans l'Entreprise")),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteurs_entreprise', to='entreprise.entreprise', verbose_name="Entreprise d'Apprentissage")),
            ],
            options={
                'verbose_name': "Tuteur d'Entreprise",
                'verbose_name_plural': "Tuteurs d'Entreprise",
            },
        ),
    ]
