# Generated by Django 5.2.7 on 2025-10-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0004_entreprise_email_entreprise_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteurentreprise',
            name='Matricule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='tuteurentreprise',
            name='date_integration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'Intégration"),
        ),
    ]
