# Generated by Django 5.2.7 on 2025-10-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0005_tuteurentreprise_matricule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
