# Generated by Django 5.2.7 on 2025-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0006_entreprise_latitude_entreprise_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='longitude',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Position'),
        ),
    ]
