# Generated by Django 5.2.7 on 2025-11-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0007_remove_entreprise_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviProspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateField(auto_now_add=True, verbose_name='Date du Suivi')),
                ('etat', models.CharField(choices=[('A_CONTACTER', 'À Contacter'), ('CONTACT_FAIT', 'Contact Fait'), ('RENDEZ_VOUS', 'Rendez-vous Planifié'), ('QUALIFIE', 'Qualifiée'), ('PERDU', 'Perdue')], default='A_CONTACTER', max_length=50, verbose_name='État de la Prospection')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes de Suivi')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospections', to='entreprise.entreprise', verbose_name='Entreprise Ciblée')),
            ],
            options={
                'verbose_name': 'Suivi de Prospection',
                'verbose_name_plural': 'Suivis de Prospection',
                'ordering': ['-date_suivi'],
            },
        ),
    ]
