# Generated by Django 5.2.7 on 2025-10-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('date_embauche', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField(blank=True, null=True)),
                ('objet', models.CharField(max_length=255)),
                ('rapport', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
            options={
                'ordering': ['-date_visite'],
                'unique_together': {('personnel', 'entreprise', 'date_visite')},
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='entreprises_visitees',
            field=models.ManyToManyField(related_name='visiteurs', through='personnel.Visite', to='entreprise.entreprise'),
        ),
    ]
