# Generated by Django 5.2.7 on 2025-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
        ('mission', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='entreprises_visitees',
            field=models.ManyToManyField(related_name='visiteurs', through='mission.Visite', to='entreprise.entreprise'),
        ),
        migrations.DeleteModel(
            name='Visite',
        ),
    ]
