# Generated by Django 5.2.7 on 2025-10-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_personnel_entreprises_visitees_delete_visite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='date_embauche',
        ),
        migrations.AddField(
            model_name='personnel',
            name='iu',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
