# Generated by Django 5.2.7 on 2025-11-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_remove_personnel_date_embauche_personnel_iu'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
