# Generated by Django 5.2.7 on 2025-10-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateTimeField(verbose_name='Date et Heure de Départ')),
                ('date_retour', models.DateTimeField(verbose_name='Date et Heure de Retour')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet de la Mission')),
                ('rapport', models.TextField(blank=True, null=True, verbose_name='Rapport de Mission')),
                ('date_visite', models.DateField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise', verbose_name='Entreprise Cible')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel', verbose_name='Personnel en Mission')),
            ],
            options={
                'verbose_name': 'Mission / Visite',
                'verbose_name_plural': 'Missions / Visites',
                'ordering': ['-date_depart'],
                'unique_together': {('personnel', 'entreprise', 'date_depart')},
            },
        ),
    ]
