# Generated by Django 5.2.7 on 2025-10-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='date_depart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et Heure de Départ'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et Heure de Retour'),
        ),
    ]
