# Generated by Django 5.2.7 on 2025-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_visite_date_depart_alter_visite_date_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='lieu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de depart'),
        ),
        migrations.AddField(
            model_name='visite',
            name='type_mission',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de Mission'),
        ),
    ]
