# Generated by Django 5.2.7 on 2025-10-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_visite_lieu_visite_type_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='moyen_transport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Moyen de Transport'),
        ),
    ]
