# Generated by Django 5.2.7 on 2025-10-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_visite_moyen_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='etat',
            field=models.BooleanField(default=False),
        ),
    ]
