# Generated by Django 5.2.7 on 2025-10-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_visite_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='etat',
            field=models.CharField(choices=[('PLANNIFIEE', 'Planifiée'), ('EN_COURS', 'En Cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANNIFIEE', max_length=50, verbose_name='État de la Mission'),
        ),
    ]
