# Generated by Django 5.2.7 on 2025-11-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_alter_visite_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='etat',
            field=models.CharField(choices=[('PLANNIFIEE', 'Planifiée'), ('EN_COURS', 'En Cours'), ('REALISE', 'Realiser'), ('ANNULEE', 'Annulée'), ('NON_REALISER', 'Non Realiser')], default='PLANNIFIEE', max_length=50, verbose_name='État de la Mission'),
        ),
    ]
